import re
from pathlib import Path

BASE_DIR = Path(__file__).parent

INDEX_HTML = BASE_DIR / "templates" / "index.html"

DEFAULT_WIDTH = 128
MAX_WIDTH = 10_000  # just to have a limitation
STD_CHAR_RAMP = (
    "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^`'. "
)
DEFAULT_NUM_CHARS = len(STD_CHAR_RAMP)
MINIMAL_CHAR_RAMP = "@#S%?*+;:,. "
IHDR_BYTES_LENGTH = 25

POLLINATIONS_URL = "https://image.pollinations.ai/prompt/{prompt}"
FILESYSTEM_UNSAFE_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')
SEPARATORS = re.compile(r"[\s\-–—,;!.]+")

WEIRD_FONTS = [
    "dcs_bfmo",
    "char4___",
    "nfi1____",
    "super_te",
    "icl-1900",
    "mnemonic",
    "rotated",
    "druid___",
    "fair_mea",
    "mcg_____",
    "d_dragon",
    "zig_zag_",
    "rampage_",
    "tecrvs__",
    "bubble_b",
    "rastan__",
    "future_3",
    "smtengwar",
    "tengwar",
    "rainbow_",
    "future_1",
    "1row",
    "beer_pub",
    "4x4_offr",
    "phonix__",
    "magic_ma",
    "z-pilot_",
    "sm______",
    "wideterm",
    "script__",
    "fp2_____",
    "f15_____",
    "heroboti",
    "star_war",
    "fairligh",
    "joust___",
    "b1ff",
    "letterw3",
    "tav1____",
    "house_of",
    "advenger",
    "dwhistled",
    "konto",
    "raw_recu",
    "char1___",
    "zone7___",
    "etcrvs__",
    "faces_of",
    "hills___",
    "green_be",
    "future_8",
    "hades___",
    "fp1_____",
    "kgames_i",
    "term",
    "hypa_bal",
    "top_duck",
    "grand_pr",
    "skateroc",
    "amc_3_liv1",
    "tomahawk",
    "hyper___",
    "fantasy_",
    "c2______",
    "stencil2",
    "future_4",
    "ts1_____",
    "bigchief",
    "unarmed_",
    "1943____",
    "future_6",
    "yie-ar__",
    "spc_demo",
    "caus_in_",
    "battle_s",
    "vortron_",
    "heavy_me",
    "ghost_bo",
    "rad_____",
    "modern__",
    "p_skateb",
    "future_5",
    "usa_pq__",
    "64f1____",
    "flyn_sh",
    "ti_pan__",
    "outrun__",
    "coil_cop",
    "kik_star",
    "future_2",
    "battlesh",
    "aquaplan",
    "skate_ro",
    "tec1____",
    "ripper",
    "convoy__",
    "subteran",
    "rok_____",
    "tec_7000",
    "atc_gran",
    "mayhem_d",
    "finalass",
    "runyc",
    "assalt_m",
    "pacos_pe",
    "inc_raw_",
    "konto_slant",
    "usa_____",
    "platoon2",
    "rockbox_",
    "high_noo",
    "street_s",
    "mig_ally",
    "ok_beer_",
    "tsm_____",
    "eftipiti",
    "rally_s2",
    "fbr1____",
    "notie_ca",
    "b_m__200",
    "platoon_",
    "runic",
    "pawn_ins",
    "asslt__m",
    "master_o",
    "wow",
    "letter_w",
    "pod_____",
    "c1______",
    "rad_phan",
    "atc_____",
    "war_of_w",
    "krak_out",
    "a_zooloo",
    "road_rai",
    "benjamin",
    "triad_st",
    "mshebrew210",
    "katakana",
    "yie_ar_k",
    "stencil1",
    "future_7",
    "panther_",
    "funky_dr",
    "rot13",
    "stealth_",
    "eftichess",
    "lexible_",
    "devilish",
    "deep_str",
    "fbr12___",
    "baz__bil",
    "fbr_stri",
    "lazy_jon",
    "ugalympi",
    "mad_nurs",
    "rally_sp",
    "npn_____",
    "tsn_base",
    "fbr_tilt",
    "skateord",
    "rci_____",
    "c_consen",
]
